trainer: forces


dataset:
  - src: /ssd/liwentao/ocp_main/tutorials/transition1x_s2ef/train/
    normalize_labels: True
    target_mean: 0       # -0.7554450631141663 这里要修改能量的均值，使得预测更加合理
    target_std: 1.0  # 2.887317180633545
    grad_target_mean: 0.0
    grad_target_std: 0.5429860192048 # 2.887317180633545
  - src: /ssd/liwentao/ocp_main/tutorials/transition1x_s2ef/test/
  - src: /ssd/liwentao/ocp_main/tutorials/transition1x_s2ef/test/


logger:
  name: wandb
  project: diff_model_benchmark


task:
  dataset: lmdb
  primary_metric: forces_mae
  labels:
    - potential energy
  grad_input: atomic forces
  train_on_free_atoms: True
  eval_on_free_atoms: True


hide_eval_progressbar: False